W4D5/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, except: [:new, :index] do 
    resources :tracks, only: [:new]
  end

  resources :tracks, except: [:new, :index]

  resource :session, only: [:new, :create, :destroy]
end

W4D5/app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :bigint(8)        not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ApplicationRecord
    validates :name, presence: true

    has_many :albums,
        class_name: :Album,
        foreign_key: :band_id,
        primary_key: :id

    has_many :tracks,
        through: :albums,
        source: :tracks   
end

W4D5/app/controllers/bands_controller.rb
class BandsController < ApplicationController

    def index
    end

    def create
        @band = Band.new(band_params)
        if @band.save
            redirect_to bands_url
        else
            flash.now[:errors] = @band.errors.full_messages
            render :new
        end
    end

    def new
        @band = Band.new
        render :new
    end

    #TODO:
    #Must be logged in to edit or destroy a band?

    def edit
        @band = Band.find(params[:id])
    end

    def show
        @band = Band.find(params[:id])
    end

    def update
        @band = Band.find(params[:id])
        if @band.update(band_params)
            redirect_to bands_url
        else
            flash.now[:errors] = @band.errors.full_messages
            render :edit
        end
    end

    def destroy
        @band = Band.find(params[:id])
        @band.destroy
        redirect_to bands_url
    end

    private
    
    def band_params
        params.require(:band).permit(:name)
    end

end

W4D5/app/views/bands/edit.html.erb
<h1>Editing <%= @band.name %></h1>

Name: <form action="<%= band_url(@band.id) %>" method="POST">
<%= auth_token %>
<input type="hidden" name="_method" value="PUT">
<input type="text" name="band[name]" value="<%= @band.name %>">
<input type="submit" value="Update">
</form>

W4D5/app/views/bands/index.html.erb
<div id="band_index">
<h1>All the bands!</h1>

<ul>
<% Band.all.each do |band| %>
    <li><a href="<%= band_url(band.id) %>"><%= band.name %> </a></li>
<% end %>
</ul>

<h2><a href="<%= new_band_url %>">Add a band</a></h2>
</div>

W4D5/app/views/bands/new.html.erb
<h1>Band Creation</h1>

<form action="<%= bands_url %>" method="POST">
<%= auth_token %>

Name: <input type="text" name="band[name]" value="">
<input type="submit" value="Create">
</form>

W4D5/app/views/bands/show.html.erb
<h1><%= @band.name %></h1>

<h2>Albums</h2>
<ul>
<% @band.albums.each do |album| %>
    <li><a href="<%= album_url(album.id) %>"><%= album.title %></a></li>
<% end %>
</ul>
<a href="<%= new_band_album_url(@band.id) %>">New Album</a>
<br> 
<br>
<a href="<%= edit_band_url(@band.id) %>">Edit this band</a>
<form action="<%= band_url(@band.id) %>" method="POST">
<%= auth_token %>
<input type="hidden" name="_method" value="DELETE">
<input type="submit" value="Delete this band">
</form>