W4D5/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, except: [:new, :index] do 
    resources :tracks, only: [:new]
  end

  resources :tracks, except: [:new, :index]

  resource :session, only: [:new, :create, :destroy]
end

W4D5/app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :bigint(8)        not null, primary key
#  title      :string           not null
#  year       :integer
#  band_id    :integer          not null
#  live       :boolean          default(FALSE), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Album < ApplicationRecord
    validates_presence_of :title, :year, :band
    validates :live, inclusion: { in: [true, false] }
    validates :title, uniqueness: { scope: :band_id }

    belongs_to :band,
        class_name: :Band,
        foreign_key: :band_id,
        primary_key: :id

    has_many :tracks,
        class_name: :Track,
        foreign_key: :album_id,
        primary_key: :id
end

W4D5/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
    def new
        @band = Band.find(params[:band_id])
        @album = Album.new(band_id: params[:band_id])
    end

    def create
        @album = Album.new(album_params)
        if @album.save
             redirect_to album_url(@album.id)
        else
            flash.now[:errors] = @album.errors.full_messages
            render :new
        end
    end

    def edit
        @album = Album.find(params[:id])
    end

    def update 
        @album = Album.find(params[:id])
        if @album.update(album_params)
            redirect_to album_url(@album.id)
        else
            flash.now[:errors] = @album.errors.full_messages
            render :edit
        end
    end

    def show
        @album = Album.find(params[:id])
    end

    def destroy
        @album = Album.find(params[:id])
        @band = @album.band
        @album.destroy
        redirect_to band_url(@band.id)
    end

    private

    def album_params
        params.require(:album).permit(:title, :year, :band_id, :live)
    end
end

W4D5/app/views/albums/edit.html.erb
<h1>Editing <%= @album.title %></h1>

<form action="<%= album_url %>" method="POST">
<%= auth_token %>
<input type="hidden" name="_method" value="PATCH">

Title: <input type="text" name="album[title]" value="<%= @album.title %>">

<select name="album[band_id]">
    <% Band.all.each do |band| %>
        <% if band.id == @album.band_id %>
            <option value="<%= band.id %>" selected><%= band.name %></option>
        <% else %>
            <option value="<%= band.id %>"><%= band.name %></option>
        <% end %>
    <% end %>
</select>

Year: <input type="text" name="album[year]" value="<%= @album.year %>">
<input type="radio" name="album[live]" value="true" <%= @album.live ? "checked" : "" %> > Live
<input type="radio" name="album[live]" value="false"<%= @album.live ? "" : "checked" %>> Studio
<input type="submit" value="Create">
</form>

W4D5/app/views/albums/new.html.erb
<h1>Album Creation</h1>

<form action="<%= albums_url %>" method="POST">
<%= auth_token %>

Title: <input type="text" name="album[title]" value="">

<select name="album[band_id]">
    <% Band.all.each do |band| %>
        <% if band.id == @album.band_id %>
            <option value="<%= band.id %>" selected><%= band.name %></option>
        <% else %>
            <option value="<%= band.id %>"><%= band.name %></option>
        <% end %>
    <% end %>
</select>

<p>Year: <input type="text" name="album[year]" value=""> </p>
<input type="radio" name="album[live]" value="true"> Live
<input type="radio" name="album[live]" value="false" checked> Studio
<input type="submit" value="Create">
</form>

W4D5/app/views/albums/show.html.erb
<h1><%= @album.title %></h1>
<h2>By: <%= @album.band.name %></h2>
<p>Year: <%= @album.year %>
    <br>
    <%= @album.live ? "Live" : "Studio" %></p>

<h2>Tracks:</h2>
<ul>
    <% @album.tracks.each do |track| %>
        <li><a href="<%= track_url(track.id) %>"><%= track.title %></a></li>
    <% end %>
</ul>
<a href="<%= new_album_track_url(@album.id) %>">Enter new track</a>
<br>
 <br>
<a href="<%= edit_album_url(@album.id) %>">Edit this album</a>

<form action="<%= album_url(@album.id) %>" method="POST">
    <%= auth_token %>
    <input type="hidden" name="_method" value="DELETE">
    <input type="submit" value="Delete this album">
</form>
<br>
<a href="<%= band_url(@album.band.id) %>">Back to band</a>